baseURL = "https://bodjaman.github.io/perch-arts/"
publishDir = "docs"
languageCode = "en-us"
title = "Perch Arts"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/perch-arts/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/perch-arts/projects/"
    weight = 2
  [[menu.main]]
    name = "Info"
    url = "/perch-arts/info/"
    weight = 3

[params]
  homeText = "Time-based Media."
