baseURL = "http://percharts.com"
languageCode = "en-us"
title = "Perch Arts"
googleAnalytics = "UA-150586843-1"
canonifyurls  = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 3

[params]
  homeText = "Time-based Media."
