baseURL = "http://example.org/"
languageCode = "en-us"
title = "Perch Arts"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 3

[params]
  homeText = "Time-based Media."
