baseURL = "http://example.org/"
languageCode = "en-us"
title = "Perch Arts"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
#    pre = "edit"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 3

#  [[menu.main]]
#    name = "Tags"
#    pre = "tag"
#    url = "/tags/"
#    weight = 3

[params]
  homeText = "Time-based Media."
