---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: datetime
  name: event_date
  label: event_date
- type: text
  name: event_time
  label: event_time
- type: textarea
  name: summary
  label: summary
- type: file
  name: featured_image
  label: featured_image
